package com.wed.entity;

public enum Preferences {
    //SOURCE
    TUTORIAL, PRESENTATIONS, SOURCE_CODE, EVENTS,

    //TOPIC
    BACKEND, FRONTEND, MOBILE,

    //BACKEND LANGUAGE
    JAVA, CP, CS, PYTHON, RUBY, NODE,

    //FRONTEND
    ANGULAR, REACT, VUE, RAZOR, NEXT,

    //MOBILE
    REACT_NATIVE, SWIFT, OBJECTIVE_C, KOTLIN, FLUTTER,

    //TARGET PLATFORM
    LINUX,MACOS,WINDOWS,

    //AREA
    EUROPE,AFRICA,AUSTRALIA,ASIA,ANTARCTICA,NORTH_AMERICA,SOUTH_AMERICA,

    //FRAMEWORK
    SPRING,NET,RUBY_RAILS,DJANGO,FLASK,NEST
}
